apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data
  awsElasticBlockStore: # for aws solution
    volumeID: <volume-id>
    fsType: ext4
