apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dev
  labels:
    app: web
spec:
  containers:
    - name: redis
      image: redis
      env:
        - name: APP_COLOR
          value: pink
        # valueFrom:
        #   configMapKeyRef:
        #     name: app-config
        #     key: APP_COLOR
        # valueFrom:
        #   secretKeyRef:
      envFrom:
        - configMapRef:
            name: app-config    #specific config map 
       